version: "3"
services:
  vprofileapp:
    image: saisri448/app
    ports:
      - "8080:8080"
  vprodb:
    image: saisri448/db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

