Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"
  config.vm.network "public_network"

config.vm.define "web1" do |web1| 
    web1.vm.box = "centos/7"
  end
config.vm.define "db" do |db|
    db.vm.box = "centos/7"
  end

config.vm.define "web2" do |web2|
    web2.vm.box = "centos/7"
  end

config.vm.define "ansible" do |ansible|
    ansible.vm.box = "ubuntu/xenial64" 
  end
end
