Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"
  config.vm.network "public_network"

  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "ubuntu/xenial64"
    jenkins.vm.hostname = "jenkins"
  end

  config.vm.define "sonar" do |sonar|
    sonar.vm.box = "ubuntu/xenial64"
    sonar.vm.hostname= "sonar"
    sonar.vm.hostname= "sonar"
    sonar.vm.provider :virtualbox do |v|
     v.customize ["modifyvm", :id, "--memory", 2100]
     end
  end
end

